<?php
declare(strict_types=1);

namespace LemurCms\Seeders;

use LemurCms\Seeder\CmsSeeder;
use LemurCms\Support\Helpers\UuidHelper;

class ComponentDefinitionsSeeder extends CmsSeeder
{
    public function run(): void
    {
        $components = [
            [
                'type' => 'container',
                'label' => 'Contenedor',
                'category' => 'layout',
                'icon' => 'layout-sidebar',
                'is_container' => 1,
                'accepts_loop' => 0,
                'default_props' => [
                    'fluid' => false,
                    'class' => '',
                ],
                'schema' => [
                    'fluid' => ['type' => 'boolean', 'label' => 'Ancho completo', 'default' => false],
                    'class' => ['type' => 'string', 'label' => 'Clases CSS adicionales', 'default' => ''],
                ],
            ],
            [
                'type' => 'row',
                'label' => 'Fila',
                'category' => 'layout',
                'icon' => 'layout-row',
                'is_container' => 1,
                'accepts_loop' => 0,
                'default_props' => [
                    'gutter' => 'g-4',
                    'align' => '',
                    'justify' => '',
                    'class' => '',
                ],
                'schema' => [
                    'gutter' => [
                        'type' => 'select',
                        'label' => 'Espaciado (Gutter)',
                        'options' => ['g-0', 'g-1', 'g-2', 'g-3', 'g-4', 'g-5'],
                        'default' => 'g-4',
                    ],
                    'align' => [
                        'type' => 'select',
                        'label' => 'Alineación vertical',
                        'options' => ['', 'align-items-start', 'align-items-center', 'align-items-end'],
                        'default' => '',
                    ],
                    'justify' => [
                        'type' => 'select',
                        'label' => 'Alineación horizontal',
                        'options' => ['', 'justify-content-start', 'justify-content-center', 'justify-content-end', 'justify-content-between', 'justify-content-around'],
                        'default' => '',
                    ],
                    'class' => ['type' => 'string', 'label' => 'Clases CSS adicionales', 'default' => ''],
                ],
            ],
            [
                'type' => 'col',
                'label' => 'Columna',
                'category' => 'layout',
                'icon' => 'layout-column',
                'is_container' => 1,
                'accepts_loop' => 0,
                'default_props' => [
                    'xs' => 12,
                    'sm' => 0,
                    'md' => 0,
                    'lg' => 0,
                    'xl' => 0,
                    'class' => '',
                ],
                'schema' => [
                    'xs' => ['type' => 'number', 'label' => 'Columnas en móvil (xs)', 'default' => 12],
                    'sm' => ['type' => 'number', 'label' => 'Columnas en tablet (sm)', 'default' => 0],
                    'md' => ['type' => 'number', 'label' => 'Columnas en escritorio medio (md)', 'default' => 0],
                    'lg' => ['type' => 'number', 'label' => 'Columnas en escritorio grande (lg)', 'default' => 0],
                    'xl' => ['type' => 'number', 'label' => 'Columnas en pantallas extra grandes (xl)', 'default' => 0],
                    'class' => ['type' => 'string', 'label' => 'Clases CSS adicionales', 'default' => ''],
                ],
            ],
            [
                'type' => 'text',
                'label' => 'Texto',
                'category' => 'content',
                'icon' => 'text',
                'is_container' => 0,
                'accepts_loop' => 1,
                'default_props' => [
                    'tag' => 'p',
                    'content' => 'Texto aquí',
                    'align' => '',
                    'class' => '',
                ],
                'schema' => [
                    'tag' => [
                        'type' => 'select',
                        'label' => 'Etiqueta HTML',
                        'options' => ['p', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6', 'span', 'small'],
                        'default' => 'p',
                    ],
                    'content' => ['type' => 'text', 'label' => 'Contenido', 'default' => 'Texto aquí'],
                    'align' => [
                        'type' => 'select',
                        'label' => 'Alineación',
                        'options' => ['', 'text-start', 'text-center', 'text-end'],
                        'default' => '',
                    ],
                    'class' => ['type' => 'string', 'label' => 'Clases CSS adicionales', 'default' => ''],
                ],
            ],
            [
                'type' => 'image',
                'label' => 'Imagen',
                'category' => 'media',
                'icon' => 'image',
                'is_container' => 0,
                'accepts_loop' => 1,
                'default_props' => [
                    'src' => '',
                    'alt' => '',
                    'fluid' => true,
                    'rounded' => false,
                    'width' => 0,
                    'height' => 0,
                    'class' => '',
                ],
                'schema' => [
                    'src' => ['type' => 'string', 'label' => 'URL de la imagen', 'default' => ''],
                    'alt' => ['type' => 'string', 'label' => 'Texto alternativo', 'default' => ''],
                    'fluid' => ['type' => 'boolean', 'label' => 'Imagen fluida (Bootstrap)', 'default' => true],
                    'rounded' => ['type' => 'boolean', 'label' => 'Bordes redondeados', 'default' => false],
                    'width' => ['type' => 'number', 'label' => 'Ancho fijo (px)', 'default' => 0],
                    'height' => ['type' => 'number', 'label' => 'Alto fijo (px)', 'default' => 0],
                    'class' => ['type' => 'string', 'label' => 'Clases CSS adicionales', 'default' => ''],
                ],
            ],
            [
                'type' => 'button',
                'label' => 'Botón',
                'category' => 'interactive',
                'icon' => 'button',
                'is_container' => 0,
                'accepts_loop' => 1,
                'default_props' => [
                    'label' => 'Click aquí',
                    'href' => '#',
                    'variant' => 'primary',
                    'size' => '',
                    'target' => '_self',
                    'class' => '',
                ],
                'schema' => [
                    'label' => ['type' => 'string', 'label' => 'Texto del botón', 'default' => 'Click aquí'],
                    'href' => ['type' => 'string', 'label' => 'Enlace de destino', 'default' => '#'],
                    'variant' => [
                        'type' => 'select',
                        'label' => 'Variante de color',
                        'options' => ['primary', 'secondary', 'success', 'danger', 'warning', 'info', 'light', 'dark', 'outline-primary', 'outline-secondary'],
                        'default' => 'primary',
                    ],
                    'size' => [
                        'type' => 'select',
                        'label' => 'Tamaño',
                        'options' => ['', 'btn-sm', 'btn-lg'],
                        'default' => '',
                    ],
                    'target' => [
                        'type' => 'select',
                        'label' => 'Destino de apertura',
                        'options' => ['_self', '_blank'],
                        'default' => '_self',
                    ],
                    'class' => ['type' => 'string', 'label' => 'Clases CSS adicionales', 'default' => ''],
                ],
            ],
            [
                'type' => 'card',
                'label' => 'Tarjeta (Card)',
                'category' => 'content',
                'icon' => 'card',
                'is_container' => 0,
                'accepts_loop' => 1,
                'default_props' => [
                    'title' => 'Título',
                    'subtitle' => '',
                    'text' => '',
                    'image_src' => '',
                    'image_alt' => '',
                    'footer' => '',
                    'class' => '',
                ],
                'schema' => [
                    'title' => ['type' => 'string', 'label' => 'Título de la tarjeta', 'default' => 'Título'],
                    'subtitle' => ['type' => 'string', 'label' => 'Subtítulo', 'default' => ''],
                    'text' => ['type' => 'text', 'label' => 'Texto del cuerpo', 'default' => ''],
                    'image_src' => ['type' => 'string', 'label' => 'URL de imagen superior', 'default' => ''],
                    'image_alt' => ['type' => 'string', 'label' => 'Texto alternativo de imagen', 'default' => ''],
                    'footer' => ['type' => 'string', 'label' => 'Texto del pie de tarjeta', 'default' => ''],
                    'class' => ['type' => 'string', 'label' => 'Clases CSS adicionales', 'default' => ''],
                ],
            ],
            [
                'type' => 'divider',
                'label' => 'Separador (Divider)',
                'category' => 'layout',
                'icon' => 'divider',
                'is_container' => 0,
                'accepts_loop' => 0,
                'default_props' => [
                    'style' => 'solid',
                    'spacing' => 'my-4',
                    'color' => '#dee2e6',
                ],
                'schema' => [
                    'style' => [
                        'type' => 'select',
                        'label' => 'Estilo de línea',
                        'options' => ['solid', 'dashed', 'dotted'],
                        'default' => 'solid',
                    ],
                    'spacing' => [
                        'type' => 'select',
                        'label' => 'Espaciado vertical',
                        'options' => ['my-1', 'my-2', 'my-3', 'my-4', 'my-5'],
                        'default' => 'my-4',
                    ],
                    'color' => ['type' => 'color', 'label' => 'Color del separador', 'default' => '#dee2e6'],
                ],
            ],
            [
                'type' => 'html',
                'label' => 'Código HTML',
                'category' => 'content',
                'icon' => 'html',
                'is_container' => 0,
                'accepts_loop' => 0,
                'default_props' => [
                    'content' => '',
                ],
                'schema' => [
                    'content' => ['type' => 'text', 'label' => 'Contenido HTML crudo', 'default' => ''],
                ],
            ],
            [
                'type' => 'accordion',
                'label' => 'Acordeón',
                'category' => 'interactive',
                'icon' => 'accordion',
                'is_container' => 1,
                'accepts_loop' => 0,
                'default_props' => [
                    'id' => '',
                    'flush' => false,
                    'always_open' => false,
                    'class' => '',
                ],
                'schema' => [
                    'id' => ['type' => 'string', 'label' => 'ID único del accordion', 'default' => ''],
                    'flush' => ['type' => 'boolean', 'label' => 'Sin bordes laterales (flush)', 'default' => false],
                    'always_open' => ['type' => 'boolean', 'label' => 'Permitir múltiples abiertos', 'default' => false],
                    'class' => ['type' => 'string', 'label' => 'Clases CSS adicionales', 'default' => ''],
                ],
            ],
            [
                'type' => 'accordion_item',
                'label' => 'Ítem de Acordeón',
                'category' => 'interactive',
                'icon' => 'accordion-item',
                'is_container' => 1,
                'accepts_loop' => 1,
                'default_props' => [
                    'title' => 'Título',
                    'open' => false,
                    'class' => '',
                ],
                'schema' => [
                    'title' => ['type' => 'string', 'label' => 'Título del ítem', 'default' => 'Título'],
                    'open' => ['type' => 'boolean', 'label' => 'Abierto por defecto', 'default' => false],
                    'class' => ['type' => 'string', 'label' => 'Clases CSS adicionales', 'default' => ''],
                ],
            ],
            [
                'type' => 'button_group',
                'label' => 'Grupo de Botones',
                'category' => 'content',
                'icon' => 'button-group',
                'is_container' => 1,
                'accepts_loop' => 0,
                'default_props' => [
                    'vertical' => false,
                    'size' => '',
                    'aria_label' => 'Grupo de botones',
                    'class' => '',
                ],
                'schema' => [
                    'vertical' => ['type' => 'boolean', 'label' => 'Orientación vertical', 'default' => false],
                    'size' => [
                        'type' => 'select',
                        'label' => 'Tamaño',
                        'options' => ['', 'btn-group-sm', 'btn-group-lg'],
                        'default' => '',
                    ],
                    'aria_label' => ['type' => 'string', 'label' => 'Label de accesibilidad', 'default' => 'Grupo de botones'],
                    'class' => ['type' => 'string', 'label' => 'Clases CSS adicionales', 'default' => ''],
                ],
            ],
            [
                'type' => 'breadcrumb',
                'label' => 'Migas de Pan',
                'category' => 'navigation',
                'icon' => 'breadcrumb',
                'is_container' => 0,
                'accepts_loop' => 0,
                'default_props' => [
                    'divider' => '/',
                    'show_home' => true,
                    'home_label' => 'Inicio',
                    'class' => '',
                ],
                'schema' => [
                    'divider' => [
                        'type' => 'select',
                        'label' => 'Carácter separador',
                        'options' => ['/', '>', '»', '—'],
                        'default' => '/',
                    ],
                    'show_home' => ['type' => 'boolean', 'label' => 'Incluir ítem de Inicio', 'default' => true],
                    'home_label' => ['type' => 'string', 'label' => 'Label del ítem raíz', 'default' => 'Inicio'],
                    'class' => ['type' => 'string', 'label' => 'Clases CSS adicionales', 'default' => ''],
                ],
            ],
            [
                'type' => 'carousel',
                'label' => 'Carrusel',
                'category' => 'media',
                'icon' => 'carousel',
                'is_container' => 1,
                'accepts_loop' => 0,
                'default_props' => [
                    'id' => '',
                    'controls' => true,
                    'indicators' => false,
                    'autoplay' => true,
                    'interval' => 5000,
                    'fade' => false,
                    'dark' => false,
                    'class' => '',
                ],
                'schema' => [
                    'id' => ['type' => 'string', 'label' => 'ID único', 'default' => ''],
                    'controls' => ['type' => 'boolean', 'label' => 'Mostrar controles', 'default' => true],
                    'indicators' => ['type' => 'boolean', 'label' => 'Mostrar indicadores', 'default' => false],
                    'autoplay' => ['type' => 'boolean', 'label' => 'Auto-avance', 'default' => true],
                    'interval' => ['type' => 'number', 'label' => 'Intervalo (ms)', 'default' => 5000],
                    'fade' => ['type' => 'boolean', 'label' => 'Transición crossfade', 'default' => false],
                    'dark' => ['type' => 'boolean', 'label' => 'Variante oscura', 'default' => false],
                    'class' => ['type' => 'string', 'label' => 'Clases CSS adicionales', 'default' => ''],
                ],
            ],
            [
                'type' => 'carousel_item',
                'label' => 'Ítem de Carrusel',
                'category' => 'media',
                'icon' => 'carousel-item',
                'is_container' => 1,
                'accepts_loop' => 1,
                'default_props' => [
                    'image_src' => '',
                    'image_alt' => '',
                    'caption_title' => '',
                    'caption_text' => '',
                    'interval' => 0,
                    'active' => false,
                ],
                'schema' => [
                    'image_src' => ['type' => 'string', 'label' => 'URL de la imagen', 'default' => ''],
                    'image_alt' => ['type' => 'string', 'label' => 'Alt de la imagen', 'default' => ''],
                    'caption_title' => ['type' => 'string', 'label' => 'Título del caption', 'default' => ''],
                    'caption_text' => ['type' => 'text', 'label' => 'Texto del caption', 'default' => ''],
                    'interval' => ['type' => 'number', 'label' => 'Intervalo (ms)', 'default' => 0],
                    'active' => ['type' => 'boolean', 'label' => 'Slide activo', 'default' => false],
                ],
            ],
            [
                'type' => 'collapse',
                'label' => 'Colapsable',
                'category' => 'interactive',
                'icon' => 'collapse',
                'is_container' => 1,
                'accepts_loop' => 0,
                'default_props' => [
                    'id' => '',
                    'trigger_label' => 'Mostrar / Ocultar',
                    'trigger_variant' => 'primary',
                    'show_trigger' => true,
                    'open' => false,
                    'class' => '',
                ],
                'schema' => [
                    'id' => ['type' => 'string', 'label' => 'ID único', 'default' => ''],
                    'trigger_label' => ['type' => 'string', 'label' => 'Texto del botón', 'default' => 'Mostrar / Ocultar'],
                    'trigger_variant' => [
                        'type' => 'select',
                        'label' => 'Variante de color',
                        'options' => ['primary', 'secondary', 'success', 'danger', 'warning', 'info', 'light', 'dark', 'outline-primary', 'outline-secondary'],
                        'default' => 'primary',
                    ],
                    'show_trigger' => ['type' => 'boolean', 'label' => 'Mostrar botón trigger', 'default' => true],
                    'open' => ['type' => 'boolean', 'label' => 'Abierto por defecto', 'default' => false],
                    'class' => ['type' => 'string', 'label' => 'Clases CSS adicionales', 'default' => ''],
                ],
            ],
            [
                'type' => 'list_group',
                'label' => 'Grupo de Listas',
                'category' => 'content',
                'icon' => 'list-group',
                'is_container' => 0,
                'accepts_loop' => 1,
                'default_props' => [
                    'flush' => false,
                    'horizontal' => '',
                    'numbered' => false,
                    'item_as_link' => false,
                    'class' => '',
                    'items' => [],
                ],
                'schema' => [
                    'flush' => ['type' => 'boolean', 'label' => 'Variante Flush', 'default' => false],
                    'horizontal' => [
                        'type' => 'select',
                        'label' => 'Horizontal',
                        'options' => ['', 'sm', 'md', 'lg', 'xl', 'xxl'],
                        'default' => '',
                    ],
                    'numbered' => ['type' => 'boolean', 'label' => 'Lista numerada', 'default' => false],
                    'item_as_link' => ['type' => 'boolean', 'label' => 'Ítems como enlaces', 'default' => false],
                    'class' => ['type' => 'string', 'label' => 'Clases CSS', 'default' => ''],
                    'items' => [
                        'type' => 'array',
                        'label' => 'Elementos de la lista',
                        'schema' => [
                            'label' => ['type' => 'string', 'label' => 'Texto', 'default' => 'Ítem'],
                            'href' => ['type' => 'string', 'label' => 'URL (si es enlace)', 'default' => ''],
                            'variant' => [
                                'type' => 'select',
                                'label' => 'Color',
                                'options' => ['', 'primary', 'secondary', 'success', 'danger', 'warning', 'info', 'light', 'dark'],
                                'default' => '',
                            ],
                            'active' => ['type' => 'boolean', 'label' => 'Activo', 'default' => false],
                            'disabled' => ['type' => 'boolean', 'label' => 'Deshabilitado', 'default' => false],
                            'badge' => ['type' => 'string', 'label' => 'Texto del Badge', 'default' => ''],
                            'badge_variant' => [
                                'type' => 'select',
                                'label' => 'Color del Badge',
                                'options' => ['primary', 'secondary', 'success', 'danger', 'warning', 'info', 'light', 'dark'],
                                'default' => 'primary',
                            ],
                        ],
                    ],
                ],
            ],
            [
                'type' => 'tooltip',
                'label' => 'Tooltip',
                'category' => 'interactive',
                'icon' => 'tooltip',
                'is_container' => 0,
                'accepts_loop' => 0,
                'default_props' => [
                    'label' => 'Tooltip',
                    'tooltip_text' => '',
                    'placement' => 'top',
                    'variant' => 'primary',
                    'class' => '',
                ],
                'schema' => [
                    'label' => ['type' => 'string', 'label' => 'Texto del elemento', 'default' => 'Tooltip'],
                    'tooltip_text' => ['type' => 'string', 'label' => 'Texto del tooltip', 'default' => ''],
                    'placement' => [
                        'type' => 'select',
                        'label' => 'Posición',
                        'options' => ['top', 'bottom', 'left', 'right'],
                        'default' => 'top',
                    ],
                    'variant' => [
                        'type' => 'select',
                        'label' => 'Variante visual',
                        'options' => ['', 'primary', 'secondary', 'success', 'danger', 'warning', 'info', 'light', 'dark', 'outline-primary', 'outline-secondary'],
                        'default' => 'primary',
                    ],
                    'class' => ['type' => 'string', 'label' => 'Clases CSS', 'default' => ''],
                ],
            ],
            [
                'type' => 'toast',
                'label' => 'Notificación (Toast)',
                'category' => 'interactive',
                'icon' => 'toast',
                'is_container' => 0,
                'accepts_loop' => 0,
                'default_props' => [
                    'id' => '',
                    'title' => 'Notificación',
                    'message' => '',
                    'time' => 'justo ahora',
                    'variant' => 'primary',
                    'autohide' => true,
                    'class' => '',
                ],
                'schema' => [
                    'id' => ['type' => 'string', 'label' => 'ID único', 'default' => ''],
                    'title' => ['type' => 'string', 'label' => 'Título', 'default' => 'Notificación'],
                    'message' => ['type' => 'text', 'label' => 'Mensaje', 'default' => ''],
                    'time' => ['type' => 'string', 'label' => 'Texto de tiempo', 'default' => 'justo ahora'],
                    'variant' => [
                        'type' => 'select',
                        'label' => 'Color del header',
                        'options' => ['primary', 'secondary', 'success', 'danger', 'warning', 'info', 'light', 'dark'],
                        'default' => 'primary',
                    ],
                    'autohide' => ['type' => 'boolean', 'label' => 'Auto-ocultar', 'default' => true],
                    'class' => ['type' => 'string', 'label' => 'Clases CSS', 'default' => ''],
                ],
            ],
            [
                'type' => 'scrollspy',
                'label' => 'Scrollspy',
                'category' => 'navigation',
                'icon' => 'scrollspy',
                'is_container' => 1,
                'accepts_loop' => 0,
                'default_props' => [
                    'id' => '',
                    'nav_id' => '',
                    'offset' => 0,
                    'class' => '',
                ],
                'schema' => [
                    'id' => ['type' => 'string', 'label' => 'ID de la zona espía', 'default' => ''],
                    'nav_id' => ['type' => 'string', 'label' => 'ID de la navegación a afectar', 'default' => ''],
                    'offset' => ['type' => 'number', 'label' => 'Offset (px)', 'default' => 0],
                    'class' => ['type' => 'string', 'label' => 'Clases CSS', 'default' => ''],
                ],
            ],
            [
                'type' => 'offcanvas',
                'label' => 'Menú Lateral',
                'category' => 'interactive',
                'icon' => 'offcanvas',
                'is_container' => 1,
                'accepts_loop' => 0,
                'default_props' => [
                    'id' => '',
                    'title' => 'Menú Lateral',
                    'placement' => 'start',
                    'backdrop' => true,
                    'body_text' => '',
                    'class' => '',
                ],
                'schema' => [
                    'id' => ['type' => 'string', 'label' => 'ID único', 'default' => ''],
                    'title' => ['type' => 'string', 'label' => 'Título', 'default' => 'Menú Lateral'],
                    'placement' => [
                        'type' => 'select',
                        'label' => 'Posición',
                        'options' => ['start', 'end', 'top', 'bottom'],
                        'default' => 'start',
                    ],
                    'backdrop' => ['type' => 'boolean', 'label' => 'Mostrar backdrop (sombra)', 'default' => true],
                    'body_text' => ['type' => 'text', 'label' => 'Texto inicial (opcional)', 'default' => ''],
                    'class' => ['type' => 'string', 'label' => 'Clases CSS', 'default' => ''],
                ],
            ],
        ];

        foreach ($components as $comp) {
            $this->firstOrCreate(
                'component_definitions',
                ['type' => $comp['type']],
                [
                    'id' => UuidHelper::v4(),
                    'label' => $comp['label'],
                    'category' => $comp['category'],
                    'icon' => $comp['icon'],
                    'default_props' => json_encode($comp['default_props']),
                    'schema' => json_encode($comp['schema']),
                    'is_container' => $comp['is_container'],
                    'accepts_loop' => $comp['accepts_loop'],
                ]
            );
        }
    }
}
